// English text made by the code (the static page text lives in the HTML, marked with data-i18n).
// Turkish is in tr.ts. {name} placeholders are filled by t().
export const EN = {
  'action.prefix': 'ACTION',
  'action.initial': 'INITIAL SUPERPOSITION',
  'action.gate': 'GATE [{gate}]',
  'action.preset': 'PRESET',
  'action.undo': 'UNDO',
  'action.angles': 'MANUAL ANGLES',
  'action.length': 'LENGTH r',
  'action.custom': 'CUSTOM Rn(α)',
  'action.once': 'MEASURE 1×',
  'action.many': 'MEASURE 1,000×',
  'action.shared': 'SHARED LINK',

  'story.initial': 'The qubit rests on the equator in the |+⟩ state, set here directly; H would bring |0⟩ to the same place. A Z-basis measurement gives |0⟩ or |1⟩ with 50% each; an X-basis measurement gives |+⟩ every time.',
  'story.X': 'Applied Pauli X (Bit Flip): rotates 180° around the X-axis. Turns the North pole (|0⟩) into the South pole (|1⟩), while |+⟩ and |−⟩, the ends of the X-axis, stay put.',
  'story.Y': 'Applied Pauli Y: 180° rotation around the Y-axis. Flips the bit like X and the phase sign like Z (Y = iXZ); |i⟩ and |−i⟩ stay put.',
  'story.Z': 'Applied Pauli Z (Phase Flip): rotates 180° around the vertical Z-axis. The probabilities of |0⟩ and |1⟩ are unchanged, but the relative phase flips: |+⟩ ↔ |−⟩.',
  'story.H': 'Applied Hadamard (H): rotates 180° around the diagonal axis halfway between X and Z. Swaps the Z and X axes: |0⟩ ↔ |+⟩, |1⟩ ↔ |−⟩.',
  'story.S': 'Applied Phase S: 90° counter-clockwise around Z, seen from |0⟩. Adds π/2 to φ; the Z-basis probabilities are unchanged.',
  'story.T': 'Applied Gate T: 45° around Z. Its matrix carries the half-angle π/8 (T = e^(iπ/8)·Rz(π/4)), hence the name "π/8 gate"; on the sphere the turn is π/4.',
  'story.Rx': 'Rotated 45° (π/4) around the X-axis. The arrow\'s Y-Z part swings from +Z toward −Y; its X-coordinate is untouched.',
  'story.Ry': 'Rotated 45° (π/4) around the Y-axis. The arrow\'s X-Z part swings from +Z toward +X; its Y-coordinate is untouched.',
  'story.custom': 'Rotated by α = {angle} around the axis n = ({nx}, {ny}, {nz}). Every single-qubit gate is such a turn, up to a global phase.',
  'story.preset': 'Preset chosen: the state is now {label}.',
  'story.presetMixed': 'Preset chosen: the arrow turned toward {label}; still mixed (r = {r}).',
  'story.reset': 'Reset: the state is |0⟩ again, a pure state at the North pole.',
  'story.undo': 'Undo applied. Restored the previous state.',
  'story.undoMeasure': 'Undo: the lab rewinds; a real measurement cannot be undone.',
  'story.angles': 'Angles set by hand: θ tilts the arrow away from |0⟩, φ turns it around the Z-axis.',
  'story.pure': 'Pure state: the arrow reaches the surface of the sphere.',
  'story.mixed': 'Mixed state: the arrow is shorter than 1 (r = {r}), so it sits inside the sphere. This is not a superposition but uncertainty about which state was prepared; at the centre every basis gives a coin toss.',
  'story.once': 'Measured in the {basis}-basis: the result was {result} (chance {p}). The state is now that pole (r = 1); unless it already sat there, measuring changed the qubit.',
  'story.many': 'Measured 1000 fresh copies in the {basis}-basis. Each copy gives one answer; the bar shows how often each came up, the black tick the prediction. The state itself is unchanged.',
  'story.shared': 'Opened from a shared link: θ = {theta}, φ = {phi}, r = {r}.',

  'label.X': 'X (BIT FLIP)',
  'label.Y': 'Y (PAULI-Y)',
  'label.Z': 'Z (PHASE FLIP)',
  'label.H': 'H (HADAMARD)',
  'label.S': 'S (PHASE π/2)',
  'label.T': 'T (π/8 GATE · π/4 TURN)',
  'label.Rx': 'Rx(π/4)',
  'label.Ry': 'Ry(π/4)',
  'label.custom': 'Rn(α)',

  'status.unmeasured': 'Unmeasured',
  'status.ready': 'Ready in {basis}-basis',
  'status.collapsed': 'Collapsed to {result}',
  'status.sampled': 'Sampled 1000 runs',
  'status.cleared': 'Histogram cleared',

  'r.pure': 'Pure',
  'r.mixed': 'Mixed',
  'formula.mixed': 'mixed: ρ = ½(I + r·σ), r = {r}; no single |ψ⟩',
  'autorotate': 'Auto-Rotate: {state}',
  'on': 'ON',
  'off': 'OFF',
  'share.copied': 'Link copied',
  'share.failed': 'Copy failed: the link is in the address bar',
  'custom.error': 'Write numbers such as 0.5π, π/4 or 0.25',
  'sp.chapterOf': 'Chapter {n} of {total}',
  'sp.minRead': '~{m} min read',
  'sp.prev': 'PREVIOUS CHAPTER',
  'sp.next': 'NEXT CHAPTER',
  'sp.mixup': '§ COMMON MIX-UP',
  'sp.math': 'SHOW THE MATHEMATICS',
  'sp.expand': '[EXPAND FORMULAS]',
  'sp.sources': 'Sources',
  'sp.fig': 'FIG.',
  'sp.theta': 'POLAR ANGLE θ',
  'sp.phi': 'AZIMUTH φ',
  'sp.r': 'LENGTH r',
  'sp.basis': 'MEASUREMENT BASIS',
  'sp.once': 'MEASURE 1×',
  'sp.many': 'MEASURE 1,000×',
  'sp.latest': 'LATEST SHOT RESULT:',
  'sp.ready': 'READY',
  'sp.total': 'Total shots: {n}',
  'sp.tick': 'Black needle: the prediction',
  'sp.gates': 'GATES',
  'sp.reset': 'RESET TO |0⟩',
  'sp.state': 'State vector: θ = {t}, φ = {p}, r = {r}',
  'sp.both': 'MEASURE BOTH 1,000×',
  'sp.qubitA': 'QUBIT A',
  'sp.qubitB': 'QUBIT B',
  'sp.t': 'ENTANGLEMENT t',
  'sp.reduced': 'Each qubit alone: |r| = {r}, Tr ρ² = {p}',
  'sp.noFigure': 'NO FIGURE IN THIS CHAPTER',
  'sp.predicted': '{basis}-basis prediction:',
  'tag.qubit': 'BITS & QUBITS',
  'tag.angles': 'STATE GEOMETRY',
  'tag.measure': 'MEASUREMENT & COLLAPSE',
  'tag.phase': 'GLOBAL & RELATIVE PHASE',
  'tag.gates': 'UNITARY ROTATIONS',
  'tag.mixed': 'PURE & MIXED STATES',
  'tag.entanglement': 'TWO QUBITS',
  'tag.limits': 'LIMITS OF THE PICTURE',
  'ref.theory': 'THEORY & QUANTUM FORMALISM',
  'ref.teaching': 'PEDAGOGY & TEACHING',
  'ref.research': 'RESEARCH ON LEARNING',
  'ref.tools': 'TOOLS & SIMULATORS',
  'ref.count': '{n} ENTRIES CATALOGUED',
  'ref.nd': 'n.d.',
} as const;

export type Key = keyof typeof EN;
