// English text made by the code (the static page text lives in the HTML, marked with data-i18n).
// Turkish is in tr.ts. {name} placeholders are filled by t().
export const EN = {
  'action.prefix': 'ACTION',
  'action.initial': 'INITIAL SUPERPOSITION',
  'action.gate': 'GATE [{gate}]',
  'action.preset': 'PRESET',
  'action.undo': 'UNDO',
  'action.angles': 'MANUAL ANGLES',
  'action.length': 'LENGTH r',
  'action.custom': 'CUSTOM Rn(α)',
  'action.once': 'MEASURE 1×',
  'action.many': 'MEASURE 1,000 COPIES',
  'action.shared': 'SHARED LINK',

  'story.initial': 'The qubit rests on the equator in the |+⟩ state, set here directly; H would bring |0⟩ to the same place. A Z-basis measurement gives |0⟩ or |1⟩ with 50% each; an X-basis measurement gives |+⟩ every time.',
  'story.X': 'Applied Pauli X (Bit Flip): rotates 180° around the X-axis. Turns the North pole (|0⟩) into the South pole (|1⟩), while |+⟩ and |−⟩, the ends of the X-axis, stay put.',
  'story.Y': 'Applied Pauli Y: 180° rotation around the Y-axis. Flips the bit like X and the phase sign like Z (Y = iXZ); |i⟩ and |−i⟩ stay put.',
  'story.Z': 'Applied Pauli Z (Phase Flip): rotates 180° around the vertical Z-axis. The probabilities of |0⟩ and |1⟩ are unchanged, but the relative phase flips: |+⟩ ↔ |−⟩.',
  'story.H': 'Applied Hadamard (H): rotates 180° around the diagonal axis halfway between X and Z. Swaps the Z and X axes: |0⟩ ↔ |+⟩, |1⟩ ↔ |−⟩.',
  'story.S': 'Applied Phase S: 90° counter-clockwise around Z, seen from |0⟩. Adds π/2 to φ; the Z-basis probabilities are unchanged.',
  'story.T': 'Applied Gate T: 45° around Z. Its matrix carries the half-angle π/8 (T = e^(iπ/8)·Rz(π/4)), hence the name "π/8 gate"; on the sphere the turn is π/4.',
  'story.Rx': 'Rotated {deg} ({a}) around the X-axis. The arrow\'s Y-Z part turns from +Z toward −Y; its X-coordinate is untouched. Rx(π) turns like X.',
  'story.Ry': 'Rotated {deg} ({a}) around the Y-axis. The arrow\'s X-Z part turns from +Z toward +X; its Y-coordinate is untouched. Ry(π) turns like Y.',
  'story.Rz': 'Rotated {deg} ({a}) around the Z-axis: φ grows by {a} and the Z-basis probabilities stay the same. Rz(π/4) turns like T and Rz(π/2) like S; the matrices differ only by a global phase, which no measurement can see.',
  'story.Sdg': 'Applied S† (S-dagger): a quarter turn back around Z (−π/2). It undoes S: S†·S = I. |+⟩ goes to |−i⟩.',
  'story.Tdg': 'Applied T† (T-dagger): an eighth turn back around Z (−π/4). It undoes T: T†·T = I.',
  'story.goto': 'Returned to step {n} ({label}) of the history. A new action from here replaces the steps after it.',
  'story.custom': 'Rotated by α = {angle} around the axis n = ({nx}, {ny}, {nz}). Every single-qubit gate is such a turn, up to a global phase.',
  'story.preset': 'Preset chosen: the state is now {label}.',
  'story.presetMixed': 'Preset chosen: the arrow turned toward {label}; still mixed (r = {r}).',
  'story.reset': 'Reset: the state is |0⟩ again, a pure state at the North pole.',
  'story.undo': 'Undo applied. Restored the previous state.',
  'story.undoMeasure': 'Undo: the lab rewinds; a real measurement cannot be undone.',
  'story.angles': 'Angles set by hand: θ tilts the arrow away from |0⟩, φ turns it around the Z-axis.',
  'story.pure': 'Pure state: the arrow reaches the surface of the sphere.',
  'story.mixed': 'Mixed state: the arrow is shorter than 1 (r = {r}), so it sits inside the sphere. This is not a superposition but uncertainty about which state was prepared; at the centre every basis gives a coin toss.',
  'story.once': 'Measured in the {basis}-basis: the result was {result} (chance {p}). The state is now that pole (r = 1); unless it already sat there, measuring changed the qubit.',
  'story.many': 'Measured {n} fresh copies in the {basis}-basis. Each copy gives one answer; the bar shows how often each came up, the black line the prediction. The state itself is unchanged.',
  'story.shared': 'Opened from a shared link: θ = {theta}, φ = {phi}, r = {r}.',

  'label.X': 'X (bit flip)',
  'label.Y': 'Y (bit + phase flip)',
  'label.Z': 'Z (phase flip)',
  'label.H': 'H (Hadamard)',
  'label.S': 'S (phase π/2)',
  'label.T': 'T (π/8 gate · π/4 turn)',
  'label.Rx': 'Rx({a})',
  'label.Ry': 'Ry({a})',
  'label.Rz': 'Rz({a})',
  'label.Sdg': 'S† (phase −π/2)',
  'label.Tdg': 'T† (−π/4 turn)',
  'history.goto': 'Return to step {n}',
  'turn.label': '{angle} about {axis}',
  'keys.list': 'Keys: X Y Z H S T apply gates · Shift+S S† · Shift+T T† · M measure once · U undo · C clear trail · R reset to |0⟩ · + and − zoom · arrows turn the view (sphere focused) · Esc closes the guide',
  'label.custom': 'Rn(α)',

  'status.unmeasured': 'Unmeasured',
  'status.ready': 'Ready in {basis}-basis',
  'status.collapsed': 'Collapsed to {result}',
  'status.sampled': 'Sampled {n} runs',
  'status.cleared': 'Histogram cleared',

  'r.pure': 'Pure',
  'r.mixed': 'Mixed',
  'r.maxMixed': 'Maximally mixed',
  'action.typed': 'TYPED VALUES',
  'measure.expect': 'Black line: expected {p} for {a}',
  'measure.spread': ' · over {n} copies a spread of about ±{s} is normal',
  'label.SX': '√X (half an X)',
  'story.SX': 'Applied √X: a quarter turn (π/2) around X. Two in a row make X. IBM\'s quantum computers use it as one of their basic gates.',
  'gate.rotSub': '{deg} about {axis}',
  'story.random': 'Jumped to a random state: θ = {theta}, φ = {phi}. Every point of the sphere was equally likely.',
  'chip.random': 'random',
  'measure.manyN': 'Measure {n} copies',
  'measure.axisErr': 'Could not read the axis. Try 1/4 or 45°; θn must be between 0 and π.',
  'story.axis': 'Measuring along the axis n = ({nx}, {ny}, {nz}) now: each shot asks "+n or −n?", with P(+n) = (1 + r·n)/2.',
  'tomo.label': 'measured',
  'tomo.out': 'Rebuilt: ({x}, {y}, {z}) ± {s} · real: ({rx}, {ry}, {rz}) · off by {d}',
  'story.tomo': 'Measured {n} copies in each of X, Y and Z and rebuilt the arrow from the averages (dashed). With more copies it lands closer to the real one: the spread shrinks like 1/√N. The qubit itself was not touched.',
  'task.start': 'Start',
  'task.again': 'Try again',
  'task.done': 'Solved',
  'task.goal': 'goal',
  'task.gates': 'Gates used: {k}',
  'task.gatesMax': 'Gates used: {k} of {m}',
  'task.solved': 'Solved! The lab confirms it.',
  'task.tooMany': 'That is more gates than this task allows. Undo, or restart.',
  'task.gatesOnly': 'This task allows gates only. Undo the last step, or restart.',
  'task.going': 'Keep going.',
  'task.flip.title': 'Flip the bit',
  'task.flip.goal': 'Start at |0⟩. Reach |1⟩ with one gate.',
  'task.plus.title': 'Make a superposition',
  'task.plus.goal': 'Start at |0⟩. Reach |+⟩, where a Z measurement is 50/50, with one gate.',
  'task.toi.title': 'Onto the Y axis',
  'task.toi.goal': 'Start at |0⟩. Reach |i⟩ with two gates.',
  'task.home.title': 'Back home',
  'task.home.goal': 'Start at |−i⟩. Bring the arrow back to |0⟩ with at most two gates.',
  'task.minus.title': 'A phase you can measure',
  'task.minus.goal': 'Start at |0⟩. Make Z measurements 50/50 while X measurements always give |−⟩. At most two gates, and no ring this time. Check your guess by measuring copies in the Measure tab (a single shot would break the task).',
  'task.odds.title': 'Three out of four',
  'task.odds.goal': 'Set the arrow so that a Z measurement gives |0⟩ three times out of four. Any tool is allowed. Hint: P(|0⟩) = cos²(θ/2).',
  'story.typedAngles': 'Set from typed angles: θ = {theta}, φ = {phi}.',
  'story.typedAmps': 'Set from the amplitudes α = {a}, β = {b}.{norm} The global phase is dropped: the sphere shows only the relative phase between |0⟩ and |1⟩.',
  'exact.normalised': ' They were divided by {n} so that |α|² + |β|² = 1.',
  'exact.errAngles': 'Could not read the angles. Try 1/3, 0.25π or 60°; θ must be between 0 and π.',
  'exact.errAmps': 'Could not read α or β. Try 1/√2, 0.6+0.8i or i/2; they cannot both be 0.',
  'formula.mixed': 'mixed: ρ = ½(I + r·σ), r = {r}; no single |ψ⟩',
  'autorotate': 'Auto-rotate: {state}',
  'on': 'ON',
  'off': 'OFF',
  'share.copied': 'Link copied',
  'share.failed': 'Copy failed: the link is in the address bar',
  'custom.error': 'Write numbers such as 0.5π, π/4 or 0.25',
  'sp.chapterOf': 'Chapter {n} of {total}',
  'sp.minRead': '~{m} min read',
  'sp.prev': 'PREVIOUS CHAPTER',
  'sp.next': 'NEXT CHAPTER',
  'sp.mixup': '§ COMMON MIX-UP',
  'sp.math': 'SHOW THE MATHEMATICS',
  'sp.expand': '[EXPAND FORMULAS]',
  'sp.sources': 'Sources',
  'sp.fig': 'FIG.',
  'sp.theta': 'Polar angle (theta)',
  'sp.phi': 'Azimuth angle (phi)',
  'sp.r': 'Length r',
  'sp.basis': 'Measurement basis',
  'sp.once': 'Measure once',
  'sp.many': 'Measure 1,000 copies',
  'sp.latest': 'Latest shot:',
  'sp.ready': 'READY',
  'sp.total': 'Total shots: {n}',
  'sp.tick': 'Black needle: the prediction',
  'sp.gates': 'Gates',
  'sp.reset': 'RESET TO |0⟩',
  'sp.state': 'State vector: θ = {t}, φ = {p}, r = {r}',
  'sp.both': 'Measure 1,000 copies of each',
  'sp.qubitA': 'QUBIT A',
  'sp.qubitB': 'QUBIT B',
  'sp.t': 'Entanglement t',
  'sp.reduced': 'Each qubit alone: |r| = {r}, Tr ρ² = {p}',
  'sp.noFigure': 'NO FIGURE IN THIS CHAPTER',
  'sp.predicted': '{basis}-basis prediction:',
  'tag.qubit': 'BITS & QUBITS',
  'tag.angles': 'STATE GEOMETRY',
  'tag.measure': 'MEASUREMENT & COLLAPSE',
  'tag.phase': 'GLOBAL & RELATIVE PHASE',
  'tag.gates': 'UNITARY ROTATIONS',
  'tag.mixed': 'PURE & MIXED STATES',
  'tag.entanglement': 'TWO QUBITS',
  'tag.limits': 'LIMITS OF THE PICTURE',
  'ref.theory': 'Theory & quantum formalism',
  'ref.teaching': 'Pedagogy & teaching',
  'ref.research': 'Research on learning',
  'ref.tools': 'Tools & simulators',
  'ref.count': '{n} entries',
  'ref.nd': 'n.d.',
} as const;

export type Key = keyof typeof EN;
