// Turkish. TR_STATIC: keys of data-i18n* attributes in the HTML pages; TR_STRINGS: keys of strings.ts.
import type { Key } from './strings';

export const TR_STATIC: Record<string, string> = {
  'lab.title': 'Bloch Küresi Simülatörü — Tek Kübit Laboratuvarı',

  // top bar
  'head.title': 'CİLT IV — BLOCH DURUM APARATI',
  'head.sub': 'Bloch Küresi Simülatörü — tek kübit için ücretsiz bir laboratuvar • Monografi Ref. PH-1964-B',
  'nav.aria': 'Sayfalar',
  'lang.aria': 'Dil',
  'intro.aria': 'Nasıl kullanılır',
  'aside.controls': 'Durum ve kapılar',
  'aside.guide': 'Kılavuz ve yorum',
  'fig.region': 'Bloch küresi',
  'state.fig': 'ŞEKİL 1-A',
  'gates.unitary': 'ÜNİTER U',
  'gate.onH': 'X+Z köşegeni',
  'custom.kind': 'EKSEN-AÇI',
  'coord': 'KOORD.',
  'nav.lab': 'LABORATUVAR',
  'nav.story': 'KURAM & HİKÂYE',
  'nav.sources': 'GÖSTERİM KAYNAKLARI',
  'head.guide': 'LAB KILAVUZU',
  'head.reset': 'KOORD. SIFIRLA',

  // intro
  'intro.text': 'Bir <strong>kübit</strong>, kuantum bilgisayarın temel birimidir. Durumu bu oktur: yukarısı <strong>|0⟩</strong>, aşağısı <strong>|1⟩</strong>; yüzeydeki diğer her nokta ikisinin bir süperpozisyonudur, içerideki noktalar ise karışık durumlardır.',
  'intro.steps': '<b class="text-primary">§ 1</b> bir durum kur · <b class="text-primary">§ 2</b> kapılarla döndür · <b class="text-primary">§ 3</b> ölç',

  // § 1 state
  'state.head': '§ 1. DURUM KOORDİNATLARI',
  'state.theta': '(Kutupsal Açı / Z ekseni)',
  'state.eq': 'π/2 (Ekv.)',
  'state.half': 'Hilbert açısı θ/2 =',
  'state.phi': '(Azimut / X-Y Fazı)',
  'state.length': 'Uzunluk',
  'state.lengthHint': '(1 = saf) :',
  'state.presets': 'Kanonik Taban Durumları',
  'preset.pz': '+Z kutbu',
  'preset.mz': '−Z kutbu',
  'preset.px': '+X ekseni',
  'preset.mx': '−X ekseni',
  'preset.py': '+Y ekseni',
  'preset.my': '−Y ekseni',
  'state.undo': 'Kapıyı Geri Al',
  'state.reset': '|0⟩ Durumuna Dön',

  // § 2 gates
  'gates.head': '§ 2. KUANTUM KAPILARI (DÖNMELER)',
  'gate.onX': 'X\'te π',
  'gate.X': 'Bit Çevirme',
  'gate.onY': 'Y\'de π',
  'gate.Y': 'Bit+Faz',
  'gate.onZ': 'Z\'de π',
  'gate.Z': 'Faz Çevirme',
  'gate.H': 'Z ↔ X takası',
  'gate.S': 'Çeyrek tur',
  'gate.T': 'Sekizde bir tur',
  'gate.Rx': 'X etrafında 45°',
  'gate.Ry': 'Y etrafında 45°',
  'custom.head': 'ÖZEL DÖNME Rn(α)',
  'custom.hint': 'Oku herhangi bir n̂(θn, φn) ekseni etrafında α açısı kadar döndür. Değerleri π cinsinden yaz.',
  'custom.theta': 'EKSEN θn',
  'custom.phi': 'EKSEN φn',
  'custom.angle': 'AÇI α',
  'custom.apply': 'UYGULA',

  // centre: sphere
  'fig.title': 'ŞEKİL 2 — BLOCH TOPUNDA DURUM VEKTÖRÜ',
  'fig.resetView': 'Görünümü Sıfırla',
  'fig.share': 'DURUMU PAYLAŞ',
  'fig.cornerA': 'BLOCH TOPU: |r| ≤ 1<br />DÖNDÜRMEK İÇİN SÜRÜKLE',
  'fig.cornerB': 'İZDÜŞÜM: ORTOGRAFİK<br />İLK GÖRÜNÜM: OKTANT I',
  'fig.aria': '3B Bloch küresi. Görünümü çevirmek için sürükle ya da ok tuşlarını kullan.',
  'fig.prepared': '|0⟩\'dan hazırlayan:',
  'fig.norm': 'Norm · Saflık:',

  // right column: guide
  'guide.head': '§ KILAVUZ & YORUM',
  'guide.exegesis': 'ŞERH',
  'guide.what': 'AZ ÖNCE NE OLDU?',
  'guide.matrix': 'OPERATÖR MATRİSİ [ U ]',
  'note.head': 'FİZİKÇİNİN NOTU: AÇININ İKİYE KATLANMASI',
  'note.text': 'Hilbert uzayında dik (ortogonal) durumlar arasındaki açı 90°\'dir. Küre her açıyı ikiye katlar: <span class="font-mono">|0⟩</span>\'dan Hilbert açısı <strong class="font-serif">θ/2</strong> kadar uzaktaki bir durum, kürede <strong class="font-serif">θ</strong> açısında durur. Bu yüzden dik durumlar, <span class="font-mono">|0⟩</span> ile <span class="font-mono">|1⟩</span> dahil, bir çapın iki zıt ucunda yer alır.',
  'math.head': 'MATEMATİĞİ GÖSTER',
  'math.map': 'Küresel koordinat dönüşümü:',
  'math.rho': 'Yoğunluk matrisi: ρ = ½ (I + x σx + y σy + z σz); burada (x, y, z) Bloch vektörü, r = √(x² + y² + z²) onun uzunluğudur.',
  'math.prob': 'Birim n ekseni boyunca sonuç olasılığı: P = (1 + x nx + y ny + z nz) / 2.',
  'guide.allSources': 'Tüm kaynaklar ve gösterim kuralları →',

  // § 3 measurement
  'measure.head': '§ 3. ÖLÇÜM & ÖRNEKLEME',
  'measure.basis': 'Taban:',
  'measure.once': '1× ÖLÇ',
  'measure.many': '1.000× ÖLÇ',
  'measure.status': 'ÇÖKÜŞ DURUMU:',
  'measure.tick': 'Mevcut durum için öngörü',
  'measure.clear': 'SAYIMI SİL',

  // footer
  'foot.build': 'BİRİNCİ BASKI • EKİM 2026',
  'foot.sources': 'KAYNAKLAR',
  'foot.code': 'KAYNAK KOD',
  'foot.licence': 'MIT LİSANSI',

  // guide modal
  'guide.close': 'Kapat',
  'modal.ref': 'MONOGRAFİ KILAVUZU REF. 1964',
  'modal.title': 'Tek Kübitin Geometrisi',
  'modal.p1': 'Kesinlikle <strong>0</strong> ya da <strong>1</strong> olan klasik bitlerin aksine, bir kuantum biti normalize edilmiş herhangi bir süperpozisyonda bulunabilir: <span class="font-serif italic text-primary">|ψ⟩ = α|0⟩ + β|1⟩</span>, öyle ki <span class="font-serif italic">|α|² + |β|² = 1</span>.',
  'modal.p2': 'Normalizasyon uzunluğu sabitlediği ve global faz gözlemlenemediği için her tek saf kübit, birim kürenin (Bloch küresi) yüzeyinde iki açıyla verilen bir noktaya karşılık gelir:',
  'modal.li1': '<strong>θ (0 ile π arası):</strong> kutupsal açı, |0⟩\'dan uzağa eğim. |0⟩ ile |1⟩ arasındaki dengeyi belirler.',
  'modal.li2': '<strong>φ (0 ile 2π arası):</strong> boylam, +X\'ten +Y\'ye doğru ölçülür. |0⟩ ile |1⟩ arasındaki bağıl faz.',
  'modal.p3': 'Kuantum mantık kapıları bu kürenin dönmeleridir. Örneğin <strong>Hadamard (H)</strong> kapısı Kuzey kutbundaki |0⟩\'ı ekvatordaki |+⟩ süperpozisyonuna çevirir.',
  'modal.p4': 'Kürenin içindeki noktalar karışık durumlardır: süperpozisyon değil, hangi durumun hazırlandığına dair belirsizlik. Ok, durumun bir resmidir; odadaki bir yön değil.',
  'modal.back': 'APARATA DÖN',

  // story page
  'story.title': 'Kuram ve Hikâye — Bloch Küresi Simülatörü',
  'story.openLab': 'LABORATUVARI AÇ',
  'story.banner': 'Cilt IV • Kuram ve Hikâye • Her biri canlı bir şekille sekiz bölüm',
  'story.contents': 'İçindekiler',
  'story.contentsHead': '§ İÇİNDEKİLER',
  'story.contentsSub': 'CİLT IV / DENEY NOTLARI',
  'story.chapters': 'Bölümler',
  'story.everyClaim': 'Her iddia bir kaynağa dayanır',
  'story.seeSources': 'Gösterim ve Kaynaklar sayfasına bak',
  'story.marginHead': '§ Kenar notu',
  'story.marginText': 'Buradaki her şekil laboratuvarın küçük bir sürümüdür. Laboratuvarda bütün kontroller bir arada.',
  'story.marginLink': 'Laboratuvarı aç →',

  // sources page
  'src.title': 'Gösterim ve Kaynaklar — Bloch Küresi Simülatörü',
  'src.appendix': '§ EK',
  'src.section': 'Cilt IV • Kısım IV-F',
  'src.head': 'Gösterim ve Kaynaklar',
  'src.lead': 'Bu aparatın kullandığı kurallar ve her iddianın nereden geldiği.',
  'src.convHead': 'KURALLAR VE GEOMETRİK İLKELER',
  'src.convLead': 'Bu simülatördeki her koordinat, durum vektörü ve kapı aşağıdaki kurallara uyar; § B’deki kaynakların kullandığı kurallar da bunlardır.',
  'src.colSymbol': 'SEMBOL / İFADE',
  'src.colMeaning': 'ANLAM VE KURAL',
  'src.row1': '<strong>Saf durum:</strong> normalize edilmiş her kübit durumu, gözlemlenemeyen global faz dışında, birim küre üzerinde bir noktadır.',
  'src.row2': '<strong>Kutupsal açı:</strong> Kuzey kutbu +Z’den (|0⟩) Güney kutbu −Z’ye (|1⟩) doğru ölçülür. Hilbert uzayındaki açı θ/2’dir.',
  'src.row3': '<strong>Azimut:</strong> ekvator düzleminde, +X’ten (|+⟩) başlayıp +Y’den (|i⟩) geçerek saat yönünün tersine ölçülür. |0⟩ ile |1⟩ arasındaki bağıl fazdır.',
  'src.row4': '<strong>Eksen durumları:</strong> |±⟩ = (|0⟩ ± |1⟩)/√2, |±i⟩ = (|0⟩ ± i|1⟩)/√2. Her çift kendi ekseninin iki zıt ucundadır.',
  'src.row5': '<strong>Bloch vektörü:</strong> bileşenleri Pauli matrislerinin beklenen değerleridir. Saf durumlarda |r| = 1, karışık durumlarda topun içinde |r| &lt; 1.',
  'src.row6': '<strong>Kapılar dönüştür:</strong> kürenin birim n ekseni etrafında, sağ el kuralıyla α kadar dönmesi. Adı olan kapılar, bir global faz dışında, böyle bir dönüşe eşittir (örn. X = i·Rx(π)).',
  'src.row7': '<strong>Ölçüm:</strong> bir eksen boyunca her sonucun olasılığı. Tek atıştan sonra durum, bulunan kutuptur.',
  'src.row8': '<strong>Saflık:</strong> yüzeydeki saf durumlarda 1, merkezdeki tam karışık ½I durumunda ½.',
  'src.refHead': 'KAYNAKLAR',
  'src.guideNo': '§ KILAVUZ 04',
  'src.indexCard': 'FİŞ',
  'src.cardHead': 'BUNLAR NASIL OKUNUR',
  'src.card1': 'Laboratuvarda ve hikâyede <strong class="font-label-sm text-label-sm bg-surface px-1 py-0.5 border border-on-surface">[1]</strong> gibi köşeli parantezli sayılar, bu sayfadaki kaynaklara işaret eder.',
  'src.cautionHead': 'GEOMETRİK AÇI UYARISI',
  'src.caution': 'Dik durumlar (<span class="font-label-sm">⟨0|1⟩ = 0</span>) kürede <strong class="font-semibold text-on-surface">180°</strong> uzaktadır, çünkü küre Hilbert uzayındaki θ/2 açısını ikiye katlar.',
  'src.measHead': 'ÖLÇÜMÜN YORUMU',
  'src.meas': 'Herhangi bir birim n ekseni boyunca ölçüm "+n mi, −n mi?" diye sorar. Spin-½ parçacık için bu, n yönüne çevrilmiş bir Stern–Gerlach mıknatısıdır; diğer kübitlerde eksen soyuttur.',
  'src.cardNo': 'FİŞ NO:',
  'src.checked': 'KAYNAKLAR DENETLENDİ:',
  'src.errataHead': 'BİR HATA MI BULDUN?',
  'src.errata': 'Fizik, ifade ya da kaynaklarla ilgili düzeltmeler memnuniyetle karşılanır.',
  'src.errataLink': 'Düzeltme gönder',
};

export const TR_STRINGS: Partial<Record<Key, string>> = {
  'action.prefix': 'İŞLEM',
  'action.initial': 'BAŞLANGIÇ SÜPERPOZİSYONU',
  'action.gate': 'KAPI [{gate}]',
  'action.preset': 'HAZIR DURUM',
  'action.undo': 'GERİ AL',
  'action.angles': 'ELLE AÇILAR',
  'action.length': 'UZUNLUK r',
  'action.custom': 'ÖZEL Rn(α)',
  'action.once': '1× ÖLÇ',
  'action.many': '1.000× ÖLÇ',
  'action.shared': 'PAYLAŞILAN BAĞLANTI',

  'story.initial': 'Kübit ekvatorda, |+⟩ durumunda duruyor; burada doğrudan ayarlandı, H de |0⟩\'ı aynı yere getirirdi. Z tabanında ölçüm %50\'şer olasılıkla |0⟩ ya da |1⟩ verir; X tabanında ölçüm ise her seferinde |+⟩ verir.',
  'story.X': 'Pauli X (Bit Çevirme) uygulandı: X ekseni etrafında 180° döndürür. Kuzey kutbunu (|0⟩) Güney kutbuna (|1⟩) çevirir; X ekseninin uçları olan |+⟩ ve |−⟩ ise yerinde kalır.',
  'story.Y': 'Pauli Y uygulandı: Y ekseni etrafında 180° dönme. Biti X gibi, faz işaretini Z gibi çevirir (Y = iXZ); |i⟩ ve |−i⟩ yerinde kalır.',
  'story.Z': 'Pauli Z (Faz Çevirme) uygulandı: dikey Z ekseni etrafında 180° döndürür. |0⟩ ve |1⟩ olasılıkları değişmez, ama bağıl faz ters döner: |+⟩ ↔ |−⟩.',
  'story.H': 'Hadamard (H) uygulandı: X ile Z\'nin tam ortasındaki çapraz eksen etrafında 180° döndürür. Z ve X eksenlerinin yerini değiştirir: |0⟩ ↔ |+⟩, |1⟩ ↔ |−⟩.',
  'story.S': 'Faz kapısı S uygulandı: |0⟩\'dan bakınca Z etrafında saat yönünün tersine 90°. φ\'ye π/2 ekler; Z tabanı olasılıkları değişmez.',
  'story.T': 'T kapısı uygulandı: Z etrafında 45°. Matrisi yarım açı π/8\'i taşır (T = e^(iπ/8)·Rz(π/4)), "π/8 kapısı" adı buradan gelir; kürede dönüş π/4\'tür.',
  'story.Rx': 'X ekseni etrafında 45° (π/4) döndürüldü. Okun Y-Z kısmı +Z\'den −Y\'ye doğru döner; X koordinatı hiç değişmez.',
  'story.Ry': 'Y ekseni etrafında 45° (π/4) döndürüldü. Okun X-Z kısmı +Z\'den +X\'e doğru döner; Y koordinatı hiç değişmez.',
  'story.custom': 'n = ({nx}, {ny}, {nz}) ekseni etrafında α = {angle} kadar döndürüldü. Her tek kübitlik kapı, bir global faz dışında, böyle bir dönüştür.',
  'story.preset': 'Hazır durum seçildi: durum artık {label}.',
  'story.presetMixed': 'Hazır durum seçildi: ok {label} yönüne döndü; durum hâlâ karışık (r = {r}).',
  'story.reset': 'Sıfırlandı: durum yine |0⟩, Kuzey kutbunda saf bir durum.',
  'story.undo': 'Geri alındı. Önceki durum geri yüklendi.',
  'story.undoMeasure': 'Geri al: laboratuvar zamanı geri sarar; gerçek bir ölçüm geri alınamaz.',
  'story.angles': 'Açılar elle ayarlandı: θ oku |0⟩\'dan uzağa eğer, φ onu Z ekseni etrafında döndürür.',
  'story.pure': 'Saf durum: ok kürenin yüzeyine ulaşıyor.',
  'story.mixed': 'Karışık durum: ok 1\'den kısa (r = {r}), bu yüzden kürenin içinde duruyor. Bu bir süperpozisyon değil, hangi durumun hazırlandığına dair belirsizlik; merkezde her taban yazı-tura verir.',
  'story.once': '{basis} tabanında ölçüldü: sonuç {result} (olasılık {p}). Durum artık o kutupta (r = 1); zaten orada değilse, ölçüm kübiti değiştirdi.',
  'story.many': 'Durumun 1000 yeni kopyası {basis} tabanında ölçüldü. Her kopya tek bir cevap verir; çubuk her cevabın ne sıklıkla çıktığını, siyah çizgi ise öngörüyü gösterir. Durumun kendisi değişmedi.',
  'story.shared': 'Paylaşılan bir bağlantıdan açıldı: θ = {theta}, φ = {phi}, r = {r}.',

  'label.X': 'X (BİT ÇEVİRME)',
  'label.Z': 'Z (FAZ ÇEVİRME)',
  'label.S': 'S (FAZ π/2)',
  'label.T': 'T (π/8 KAPISI · π/4 DÖNÜŞ)',

  'status.unmeasured': 'Ölçülmedi',
  'status.ready': '{basis} tabanında hazır',
  'status.collapsed': '{result} durumuna çöktü',
  'status.sampled': '1000 ölçüm örneklendi',
  'status.cleared': 'Histogram temizlendi',

  'r.pure': 'Saf',
  'r.mixed': 'Karışık',
  'formula.mixed': 'karışık: ρ = ½(I + r·σ), r = {r}; tek bir |ψ⟩ yok',
  'autorotate': 'Oto-Dönüş: {state}',
  'on': 'AÇIK',
  'off': 'KAPALI',
  'share.copied': 'Bağlantı kopyalandı',
  'share.failed': 'Kopyalanamadı: bağlantı adres çubuğunda',
  'custom.error': '0,5π, π/4 ya da 0,25 gibi sayılar yaz',
  'sp.chapterOf': 'Bölüm {n} / {total}',
  'sp.minRead': '~{m} dk okuma',
  'sp.prev': 'ÖNCEKİ BÖLÜM',
  'sp.next': 'SONRAKİ BÖLÜM',
  'sp.mixup': '§ YAYGIN KARIŞIKLIK',
  'sp.math': 'MATEMATİĞİ GÖSTER',
  'sp.expand': '[FORMÜLLERİ AÇ]',
  'sp.sources': 'Kaynaklar',
  'sp.fig': 'ŞEKİL',
  'sp.theta': 'KUTUPSAL AÇI θ',
  'sp.phi': 'AZİMUT φ',
  'sp.r': 'UZUNLUK r',
  'sp.basis': 'ÖLÇÜM TABANI',
  'sp.once': '1× ÖLÇ',
  'sp.many': '1.000× ÖLÇ',
  'sp.latest': 'SON ATIŞ SONUCU:',
  'sp.ready': 'HAZIR',
  'sp.total': 'Toplam atış: {n}',
  'sp.tick': 'Siyah iğne: öngörü',
  'sp.gates': 'KAPILAR',
  'sp.reset': '|0⟩ DURUMUNA DÖN',
  'sp.state': 'Durum vektörü: θ = {t}, φ = {p}, r = {r}',
  'sp.both': 'İKİSİNİ DE 1.000× ÖLÇ',
  'sp.qubitA': 'KÜBİT A',
  'sp.qubitB': 'KÜBİT B',
  'sp.t': 'DOLANIKLIK t',
  'sp.reduced': 'Her kübit tek başına: |r| = {r}, Tr ρ² = {p}',
  'sp.noFigure': 'BU BÖLÜMDE ŞEKİL YOK',
  'sp.predicted': '{basis} tabanı öngörüsü:',
  'tag.qubit': 'BİTLER VE KÜBİTLER',
  'tag.angles': 'DURUM GEOMETRİSİ',
  'tag.measure': 'ÖLÇÜM VE ÇÖKÜŞ',
  'tag.phase': 'GLOBAL VE BAĞIL FAZ',
  'tag.gates': 'ÜNİTER DÖNMELER',
  'tag.mixed': 'SAF VE KARIŞIK DURUMLAR',
  'tag.entanglement': 'İKİ KÜBİT',
  'tag.limits': 'RESMİN SINIRLARI',
  'ref.theory': 'KURAM VE KUANTUM FORMALİZMİ',
  'ref.teaching': 'ÖĞRETİM VE PEDAGOJİ',
  'ref.research': 'ÖĞRENME ARAŞTIRMALARI',
  'ref.tools': 'ARAÇLAR VE SİMÜLATÖRLER',
  'ref.count': '{n} KAYIT',
  'ref.nd': 't.y.',
};
