// Turkish. TR_STATIC: keys of data-i18n* attributes in the HTML pages; TR_STRINGS: keys of strings.ts.
import type { Key } from './strings';

export const TR_STATIC: Record<string, string> = {
  'lab.title': 'Bloch Küresi Simülatörü — Tek Kübit Laboratuvarı',

  // lab workbench (Stitch eebad484)
  'lab.brand': 'Bloch Lab',
  'tab.lab': 'Lab',
  'tab.story': 'Kuram ve Hikâye',
  'tab.sources': 'Gösterim ve Kaynaklar',
  'head.guideAria': 'Laboratuvar kılavuzu',
  'fig.no': 'Şekil 1',
  'hist.undo': 'Geri al',
  'hist.reset': 'Sıfırla',
  'hist.clear': 'Temizle',
  'bases.basis': 'Taban',
  'fig.coords': 'Koordinatlar',
  'guide.interp': 'Yorum',
  'tab.aria': 'Kontroller',
  'tab.state': 'Durum',
  'tab.gates': 'Kapılar',
  'tab.measure': 'Ölçüm',
  'gate.turn': 'dönüş',
  'gate.reset': 'Sıfırla',
  'measure.warn': '<strong class="text-on-surface">Ölçüm kübiti değiştirir:</strong> ok cevaba atlar. Olasılıkları kübite dokunmadan görmek için kopya ölç.',
  'measure.choose': 'Ölçüm tabanı',
  'math.drawer': 'Matematik ve kaynaklar',

  'gates.pauli': 'Pauli',
  'gates.sqrt': 'Karekök',
  'gates.angle': 'Dönme açısı',
  'gate.SX': 'Yarım X',
  'tab.tasks': 'Görevler',
  'tasks.head': 'Görevler',
  'tasks.lead': 'Kısa alıştırmalar. Küredeki halka hedefi gösterir; laboratuvar her adımı denetler.',
  'task.restart': 'Baştan',
  'task.stop': 'Bırak',
  'state.random': 'Rastgele durum',
  'measure.custom': 'n (özel)',
  'measure.copies': 'Kopya:',
  'measure.axisHint': 'n ekseni, π cinsinden (1/4 = π/4) ya da derece olarak (45°). Kürede kesikli çizgiyle görünür.',
  'tomo.head': 'Oku ölçümlerden bul',
  'tomo.hint': 'Seçili sayıda kopyayı X\'te, Y\'de ve Z\'de ölçer, sonra oku yeniden kurar: her koordinat 2·P(+) − 1. Gerçek laboratuvarlar kübitin durumunu böyle bulur, çünkü okun kendisini kimse göremez.',
  'tomo.btn': 'Oku yeniden kur',
  'rho.head': 'Yoğunluk matrisi ρ',
  'rho.note': 'Köşegen: Z olasılıkları. Köşegen dışı: X ve Y kısımları; durum karıştıkça 0\'a doğru küçülürler.',
  'gates.rule': 'Bütün dönmeler sağ el kuralına göre: eksen sana bakarken saat yönünün tersine.',
  'gates.hadamard': 'Hadamard',
  'gates.phase': 'Z etrafında faz dönüşleri',
  'gates.rot': 'Dönmeler',
  'fig.zoomIn': 'Yakınlaştır',
  'fig.zoomOut': 'Uzaklaştır',
  'fig.zoomInTip': 'Yakınlaştır (+, tekerlek, iki parmak)',
  'fig.zoomOutTip': 'Uzaklaştır (−, tekerlek, iki parmak)',

  // notice under the header
  'notice.close': 'Duyuruyu kapat',
  'notice.title': 'Önemli not',
  'notice.lead': 'Bu site hâlâ yapım aşamasında, bu yüzden bazı özellikler henüz tam çalışmayabilir.',
  'notice.text': 'Bir sorunla karşılaşırsan ya da bir önerin olursa <a class="underline font-semibold hover:text-primary" href="https://github.com/mertcincinoglu/Bloch-Sphere-Simulator/issues" target="_blank" rel="noopener">GitHub</a> üzerinden paylaşabilir ya da <a class="underline font-semibold hover:text-primary" href="mailto:contact@mertcincinoglu.com">contact@mertcincinoglu.com</a> adresine e-posta gönderebilirsin. Geri bildirimin siteyi geliştirmeme çok yardımcı oluyor.',
  'notice.thanks': 'Siteyi herkes için daha iyi hâle getirirken gösterdiğin sabır ve destek için teşekkürler!',

  // top bar
  'head.title': 'CİLT IV — BLOCH DURUM APARATI',
  'head.sub': 'Bloch Küresi Simülatörü — tek kübit için ücretsiz bir laboratuvar • Monografi Ref. PH-1964-B',
  'nav.aria': 'Sayfalar',
  'lang.aria': 'Dil',
  'intro.aria': 'Nasıl kullanılır',
  'aside.controls': 'Durum ve kapılar',
  'aside.guide': 'Kılavuz ve yorum',
  'fig.region': 'Bloch küresi',
  'state.fig': 'ŞEKİL 1-A',
  'gates.unitary': 'ÜNİTER U',
  'gate.onH': 'X+Z köşegeni',
  'custom.kind': 'EKSEN-AÇI',
  'coord': 'KOORD.',
  'nav.lab': 'LABORATUVAR',
  'nav.story': 'KURAM & HİKÂYE',
  'nav.sources': 'GÖSTERİM KAYNAKLARI',
  'head.guide': 'LAB KILAVUZU',
  'head.reset': 'KOORD. SIFIRLA',

  // intro
  'intro.text': 'Bir <strong>kübit</strong>, kuantum bilgisayarın temel birimidir. Durumu bu oktur: yukarısı <strong>|0⟩</strong>, aşağısı <strong>|1⟩</strong>; yüzeydeki diğer her nokta ikisinin bir süperpozisyonudur, içerideki noktalar ise karışık durumlardır.',
  'intro.steps': '<b class="text-primary">§ 1</b> bir durum kur · <b class="text-primary">§ 2</b> kapılarla döndür · <b class="text-primary">§ 3</b> ölç',

  // § 1 state
  'state.head': 'Açılar ve uzunluk',
  'state.theta': 'Kutupsal açı, diğer adıyla teta (+Z\'den)',
  'state.eq': 'ekvator',
  'state.half': 'Hilbert açısı θ/2 =',
  'state.phi': 'Azimut açısı, diğer adıyla fi (+X\'ten +Y\'ye)',
  'state.length': 'Uzunluk',
  'state.lengthHint': '(1 = saf) :',
  'state.phiNote': 'φ aynı zamanda |0⟩ ile |1⟩ arasındaki <strong>bağıl fazdır</strong>: Z ölçümünü değiştirmez, X ve Y ölçümlerini değiştirir.',
  'state.probZ': 'Z ölçümünde:',
  'exact.head': 'Değerleri yazarak gir',
  'exact.anglesHint': 'Açılar π cinsinden (1/3 = π/3) ya da derece olarak (60°).',
  'exact.ampsHint': 'Ya da |ψ⟩ = α|0⟩ + β|1⟩ genliklerini yaz. Karmaşık sayılar olur: <b>1/√2</b>, <b>0.6+0.8i</b>, <b>i/2</b>. Normalize etmeyi site yapar.',
  'state.presets': 'Eksen durumları (tek tıkla)',
  'preset.pz': '+Z kutbu',
  'preset.mz': '−Z kutbu',
  'preset.px': '+X ekseni',
  'preset.mx': '−X ekseni',
  'preset.py': '+Y ekseni',
  'preset.my': '−Y ekseni',
  'state.undo': 'Kapıyı Geri Al',
  'state.reset': '|0⟩ Durumuna Dön',

  // § 2 gates
  'gates.head': 'Üniter operatörler',
  'gate.onX': 'X\'te π',
  'gate.X': 'Bit çevirme',
  'gate.onY': 'Y\'de π',
  'gate.Y': 'Bit+faz',
  'gate.onZ': 'Z\'de π',
  'gate.Z': 'Faz çevirme',
  'gate.H': 'Z ↔ X takası',
  'gate.S': 'Çeyrek tur',
  'gate.T': 'Sekizde bir tur',
  'gate.Rx': 'X etrafında 45°',
  'gate.Ry': 'Y etrafında 45°',
  'gate.Rz': 'Z etrafında 45°',
  'gate.Sdg': 'Çeyrek tur geri',
  'gate.Tdg': 'Sekizde bir tur geri',
  'gates.keys': '<b class="text-primary">Tuşlar:</b> X Y Z H S T · Shift+S S† · Shift+T T† · M ölç · U geri al · C izi sil · R sıfırla · + − yakınlaştır · ? tüm tuşlar',
  'custom.head': 'Özel dönme Rn(α)',
  'custom.hint': 'Oku herhangi bir n̂(θn, φn) ekseni etrafında α açısı kadar döndür. Değerleri π cinsinden yaz.',
  'custom.theta': 'Eksen θn',
  'custom.phi': 'Eksen φn',
  'custom.angle': 'Açı α',
  'custom.apply': 'Uygula',

  // centre: sphere
  'fig.title': 'Bloch topunda durum vektörü',
  'fig.resetView': 'Görünümü sıfırla',
  'fig.share': 'Durumu paylaş',
  'fig.clearTrail': 'İzi sil',
  'fig.history': 'Geçmiş:',
  'fig.historyAria': 'Geçmiş',
  'fig.dial': 'Bağıl faz',
  'fig.cornerA': 'BLOCH TOPU: |r| ≤ 1<br />DÖNDÜRMEK İÇİN SÜRÜKLE',
  'fig.cornerB': 'İZDÜŞÜM: ORTOGRAFİK<br />İLK GÖRÜNÜM: OKTANT I',
  'fig.aria': '3B Bloch küresi. Görünümü çevirmek için sürükle ya da ok tuşlarını kullan; yakınlaştırmak için tekerleği çevir ya da iki parmakla sıkıştır.',
  'fig.prepared': '|0⟩\'dan hazırlayan:',
  'fig.norm': 'Norm · Saflık:',

  // right column: guide
  'guide.head': '§ KILAVUZ & YORUM',
  'guide.exegesis': 'ŞERH',
  'guide.what': 'AZ ÖNCE NE OLDU?',
  'guide.matrix': 'Operatör matrisi [ U ]',
  'note.head': 'Fizikçinin notu: açının ikiye katlanması',
  'note.text': 'Hilbert uzayında dik (ortogonal) durumlar arasındaki açı 90°\'dir. Küre her açıyı ikiye katlar: <span class="font-mono">|0⟩</span>\'dan Hilbert açısı <strong class="font-serif">θ/2</strong> kadar uzaktaki bir durum, kürede <strong class="font-serif">θ</strong> açısında durur. Bu yüzden dik durumlar, <span class="font-mono">|0⟩</span> ile <span class="font-mono">|1⟩</span> dahil, bir çapın iki zıt ucunda yer alır.',
  'math.head': 'MATEMATİĞİ GÖSTER',
  'math.map': 'Küresel koordinat dönüşümü:',
  'math.rho': 'Yoğunluk matrisi: ρ = ½ (I + x σx + y σy + z σz); burada (x, y, z) Bloch vektörü, r = √(x² + y² + z²) onun uzunluğudur.',
  'math.prob': 'Birim n ekseni boyunca sonuç olasılığı: P = (1 + x nx + y ny + z nz) / 2.',
  'guide.allSources': 'Tüm kaynaklar ve gösterim kuralları →',

  // § 3 measurement
  'measure.head': '§ 3. ÖLÇÜM & ÖRNEKLEME',
  'measure.basis': 'Taban:',
  'measure.once': 'Bir kez ölç',
  'measure.many': '1.000 kopyayı ölç',
  'measure.status': 'Son ölçüm:',
  'measure.tick': 'Mevcut durum için öngörü',
  'measure.clear': 'Sayımı sil',

  // footer
  'foot.build': 'Birinci baskı • Ekim 2026',
  'foot.sources': 'Kaynaklar',
  'foot.code': 'Kaynak kod',
  'foot.licence': 'MIT lisansı',

  // guide modal
  'guide.close': 'Kapat',
  'modal.ref': 'MONOGRAFİ KILAVUZU REF. 1964',
  'modal.title': 'Tek Kübitin Geometrisi',
  'modal.p1': 'Kesinlikle <strong>0</strong> ya da <strong>1</strong> olan klasik bitlerin aksine, bir kuantum biti normalize edilmiş herhangi bir süperpozisyonda bulunabilir: <span class="font-serif italic text-primary">|ψ⟩ = α|0⟩ + β|1⟩</span>, öyle ki <span class="font-serif italic">|α|² + |β|² = 1</span>.',
  'modal.p2': 'Normalizasyon uzunluğu sabitlediği ve global faz gözlemlenemediği için her tek saf kübit, birim kürenin (Bloch küresi) yüzeyinde iki açıyla verilen bir noktaya karşılık gelir:',
  'modal.li1': '<strong>θ (0 ile π arası):</strong> kutupsal açı, |0⟩\'dan uzağa eğim. |0⟩ ile |1⟩ arasındaki dengeyi belirler.',
  'modal.li2': '<strong>φ (0 ile 2π arası):</strong> boylam, +X\'ten +Y\'ye doğru ölçülür. |0⟩ ile |1⟩ arasındaki bağıl faz.',
  'modal.p3': 'Kuantum mantık kapıları bu kürenin dönmeleridir. Örneğin <strong>Hadamard (H)</strong> kapısı Kuzey kutbundaki |0⟩\'ı ekvatordaki |+⟩ süperpozisyonuna çevirir.',
  'modal.p4': 'Kürenin içindeki noktalar karışık durumlardır: süperpozisyon değil, hangi durumun hazırlandığına dair belirsizlik. Ok, durumun bir resmidir; odadaki bir yön değil.',
  'modal.back': 'APARATA DÖN',

  // story page
  'story.title': 'Kuram ve Hikâye — Bloch Küresi Simülatörü',
  'story.openLab': 'LABORATUVARI AÇ',
  'story.banner': 'Kuram ve Hikâye • Her biri canlı bir şekille sekiz bölüm',
  'story.contents': 'İçindekiler',
  'story.contentsHead': '§ İÇİNDEKİLER',
  'story.contentsSub': 'CİLT IV / DENEY NOTLARI',
  'story.chapters': 'Bölümler',
  'story.everyClaim': 'Her iddia bir kaynağa dayanır',
  'story.seeSources': 'Gösterim ve Kaynaklar sayfasına bak',
  'story.marginHead': '§ Kenar notu',
  'story.marginText': 'Buradaki her şekil laboratuvarın küçük bir sürümüdür. Laboratuvarda bütün kontroller bir arada.',
  'story.marginLink': 'Laboratuvarı aç →',

  // sources page
  'src.title': 'Gösterim ve Kaynaklar — Bloch Küresi Simülatörü',
  'src.head': 'Gösterim ve Kaynaklar',
  'src.lead': 'Bu simülatörün kullandığı kurallar ve her iddianın nereden geldiği.',
  'src.convHead': 'Kurallar ve geometrik ilkeler',
  'src.convLead': 'Bu simülatördeki her koordinat, durum vektörü ve kapı aşağıdaki kurallara uyar; § B’deki kaynakların kullandığı kurallar da bunlardır.',
  'src.colSymbol': 'Sembol / ifade',
  'src.colMeaning': 'Anlam ve kural',
  'src.row1': '<strong>Saf durum:</strong> normalize edilmiş her kübit durumu, gözlemlenemeyen global faz dışında, birim küre üzerinde bir noktadır.',
  'src.row2': '<strong>Kutupsal açı:</strong> Kuzey kutbu +Z’den (|0⟩) Güney kutbu −Z’ye (|1⟩) doğru ölçülür. Hilbert uzayındaki açı θ/2’dir.',
  'src.row3': '<strong>Azimut:</strong> ekvator düzleminde, +X’ten (|+⟩) başlayıp +Y’den (|i⟩) geçerek saat yönünün tersine ölçülür. |0⟩ ile |1⟩ arasındaki bağıl fazdır.',
  'src.row4': '<strong>Eksen durumları:</strong> |±⟩ = (|0⟩ ± |1⟩)/√2, |i⟩ = (|0⟩ + i|1⟩)/√2, |−i⟩ = (|0⟩ − i|1⟩)/√2 (bazı kitaplar |+i⟩ ve |−i⟩ yazar). Her çift kendi ekseninin iki zıt ucundadır.',
  'src.row5': '<strong>Bloch vektörü:</strong> bileşenleri Pauli matrislerinin beklenen değerleridir. Saf durumlarda |r| = 1, karışık durumlarda topun içinde |r| &lt; 1.',
  'src.row6': '<strong>Kapılar dönüştür:</strong> kürenin birim n ekseni etrafında, sağ el kuralıyla α kadar dönmesi. Adı olan kapılar, bir global faz dışında, böyle bir dönüşe eşittir (örn. X = i·Rx(π)).',
  'src.row7': '<strong>Ölçüm:</strong> bir eksen boyunca her sonucun olasılığı. Tek atıştan sonra durum, bulunan kutuptur.',
  'src.row8': '<strong>Saflık:</strong> yüzeydeki saf durumlarda 1, merkezdeki tam karışık ½I durumunda ½.',
  'src.refHead': 'Kaynaklar',
  'src.cardHead': 'Bunlar nasıl okunur',
  'src.card1': 'Laboratuvarda ve hikâyede <strong class="font-label-sm text-label-sm bg-surface px-1 py-0.5 border border-on-surface">[1]</strong> gibi köşeli parantezli sayılar, bu sayfadaki kaynaklara işaret eder.',
  'src.cautionHead': 'Açılarla ilgili bir uyarı',
  'src.caution': 'Dik durumlar (<span class="font-label-sm">⟨0|1⟩ = 0</span>) kürede <strong class="font-semibold text-on-surface">180°</strong> uzaktadır, çünkü küre Hilbert uzayındaki θ/2 açısını ikiye katlar.',
  'src.measHead': 'Ölçüm ne sorar',
  'src.meas': 'Herhangi bir birim n ekseni boyunca ölçüm "+n mi, −n mi?" diye sorar. Spin-½ parçacık için bu, n yönüne çevrilmiş bir Stern–Gerlach mıknatısıdır; diğer kübitlerde eksen soyuttur.',
  'src.checked': 'Kaynaklar denetlendi:',
  'src.errataHead': 'Bir hata mı buldun?',
  'src.errata': 'Fizik, ifade ya da kaynaklarla ilgili düzeltmeler memnuniyetle karşılanır.',
  'src.errataLink': 'Düzeltme gönder',
};

export const TR_STRINGS: Partial<Record<Key, string>> = {
  'action.prefix': 'İŞLEM',
  'action.initial': 'BAŞLANGIÇ SÜPERPOZİSYONU',
  'action.gate': 'KAPI [{gate}]',
  'action.preset': 'HAZIR DURUM',
  'action.undo': 'GERİ AL',
  'action.angles': 'ELLE AÇILAR',
  'action.length': 'UZUNLUK r',
  'action.custom': 'ÖZEL Rn(α)',
  'action.once': '1× ÖLÇ',
  'action.many': '1.000 KOPYAYI ÖLÇ',
  'action.shared': 'PAYLAŞILAN BAĞLANTI',

  'story.initial': 'Kübit ekvatorda, |+⟩ durumunda duruyor; burada doğrudan ayarlandı, H de |0⟩\'ı aynı yere getirirdi. Z tabanında ölçüm %50\'şer olasılıkla |0⟩ ya da |1⟩ verir; X tabanında ölçüm ise her seferinde |+⟩ verir.',
  'story.X': 'Pauli X (Bit Çevirme) uygulandı: X ekseni etrafında 180° döndürür. Kuzey kutbunu (|0⟩) Güney kutbuna (|1⟩) çevirir; X ekseninin uçları olan |+⟩ ve |−⟩ ise yerinde kalır.',
  'story.Y': 'Pauli Y uygulandı: Y ekseni etrafında 180° dönme. Biti X gibi, faz işaretini Z gibi çevirir (Y = iXZ); |i⟩ ve |−i⟩ yerinde kalır.',
  'story.Z': 'Pauli Z (Faz Çevirme) uygulandı: dikey Z ekseni etrafında 180° döndürür. |0⟩ ve |1⟩ olasılıkları değişmez, ama bağıl faz ters döner: |+⟩ ↔ |−⟩.',
  'story.H': 'Hadamard (H) uygulandı: X ile Z\'nin tam ortasındaki çapraz eksen etrafında 180° döndürür. Z ve X eksenlerinin yerini değiştirir: |0⟩ ↔ |+⟩, |1⟩ ↔ |−⟩.',
  'story.S': 'Faz kapısı S uygulandı: |0⟩\'dan bakınca Z etrafında saat yönünün tersine 90°. φ\'ye π/2 ekler; Z tabanı olasılıkları değişmez.',
  'story.T': 'T kapısı uygulandı: Z etrafında 45°. Matrisi yarım açı π/8\'i taşır (T = e^(iπ/8)·Rz(π/4)), "π/8 kapısı" adı buradan gelir; kürede dönüş π/4\'tür.',
  'story.Rx': 'X ekseni etrafında {deg} ({a}) döndürüldü. Okun Y-Z kısmı +Z\'den −Y\'ye doğru döner; X koordinatı değişmez. Rx(π), X ile aynı dönüşü yapar.',
  'story.Ry': 'Y ekseni etrafında {deg} ({a}) döndürüldü. Okun X-Z kısmı +Z\'den +X\'e doğru döner; Y koordinatı değişmez. Ry(π), Y ile aynı dönüşü yapar.',
  'story.Rz': 'Z ekseni etrafında {deg} ({a}) döndürüldü: φ, {a} kadar artar, Z tabanı olasılıkları değişmez. Rz(π/4) T ile, Rz(π/2) S ile aynı dönüşü yapar; matrisler yalnız hiçbir ölçümün göremediği bir global fazla ayrılır.',
  'story.Sdg': 'S† (S-hançer) uygulandı: Z etrafında çeyrek tur geri (−π/2). S\'yi geri alır: S†·S = I. |+⟩, |−i⟩ olur.',
  'story.Tdg': 'T† (T-hançer) uygulandı: Z etrafında sekizde bir tur geri (−π/4). T\'yi geri alır: T†·T = I.',
  'story.goto': 'Geçmişin {n}. adımına ({label}) dönüldü. Buradan yapılan yeni bir işlem sonraki adımların yerini alır.',
  'story.custom': 'n = ({nx}, {ny}, {nz}) ekseni etrafında α = {angle} kadar döndürüldü. Her tek kübitlik kapı, bir global faz dışında, böyle bir dönüştür.',
  'story.preset': 'Hazır durum seçildi: durum artık {label}.',
  'story.presetMixed': 'Hazır durum seçildi: ok {label} yönüne döndü; durum hâlâ karışık (r = {r}).',
  'story.reset': 'Sıfırlandı: durum yine |0⟩, Kuzey kutbunda saf bir durum.',
  'story.undo': 'Geri alındı. Önceki durum geri yüklendi.',
  'story.undoMeasure': 'Geri al: laboratuvar zamanı geri sarar; gerçek bir ölçüm geri alınamaz.',
  'story.angles': 'Açılar elle ayarlandı: θ oku |0⟩\'dan uzağa eğer, φ onu Z ekseni etrafında döndürür.',
  'story.pure': 'Saf durum: ok kürenin yüzeyine ulaşıyor.',
  'story.mixed': 'Karışık durum: ok 1\'den kısa (r = {r}), bu yüzden kürenin içinde duruyor. Bu bir süperpozisyon değil, hangi durumun hazırlandığına dair belirsizlik; merkezde her taban yazı-tura verir.',
  'story.once': '{basis} tabanında ölçüldü: sonuç {result} (olasılık {p}). Durum artık o kutupta (r = 1); zaten orada değilse, ölçüm kübiti değiştirdi.',
  'story.many': '{basis} tabanında {n} taze kopya ölçüldü. Her kopya tek bir cevap verir; çubuk her cevabın ne sıklıkla geldiğini, siyah çizgi öngörüyü gösterir. Durumun kendisi değişmez.',
  'story.shared': 'Paylaşılan bir bağlantıdan açıldı: θ = {theta}, φ = {phi}, r = {r}.',

  'label.X': 'X (bit çevirme)',
  'label.Y': 'Y (bit + faz çevirme)',
  'label.H': 'H (Hadamard)',
  'label.Z': 'Z (faz çevirme)',
  'label.S': 'S (faz π/2)',
  'label.T': 'T (π/8 kapısı · π/4 dönüş)',
  'label.Rz': 'Rz({a})',
  'label.Ry': 'Ry({a})',
  'label.Rx': 'Rx({a})',
  'label.Sdg': 'S† (faz −π/2)',
  'label.Tdg': 'T† (−π/4 dönüş)',
  'history.goto': '{n}. adıma dön',
  'turn.label': '{axis} etrafında {angle}',
  'keys.list': 'Tuşlar: X Y Z H S T kapı uygular · Shift+S S† · Shift+T T† · M bir kez ölç · U geri al · C izi sil · R |0⟩\'a sıfırla · + ve − yakınlaştırır · oklar görünümü çevirir (küre seçiliyken) · Esc rehberi kapatır',

  'status.unmeasured': 'Ölçülmedi',
  'status.ready': '{basis} tabanında hazır',
  'status.collapsed': '{result} durumuna çöktü',
  'status.sampled': '{n} ölçüm örneklendi',
  'status.cleared': 'Histogram temizlendi',

  'r.pure': 'Saf',
  'r.mixed': 'Karışık',
  'r.maxMixed': 'Tam karışık',
  'action.typed': 'YAZILAN DEĞERLER',
  'measure.expect': 'Siyah çizgi: {a} için beklenen {p}',
  'measure.spread': ' · {n} kopyada yaklaşık ±{s} sapma normaldir',
  'label.SX': '√X (yarım X)',
  'story.SX': '√X uygulandı: X etrafında çeyrek tur (π/2). Art arda iki tanesi X eder. IBM\'in kuantum bilgisayarları bunu temel kapılarından biri olarak kullanır.',
  'gate.rotSub': '{axis} etrafında {deg}',
  'story.random': 'Rastgele bir duruma geçildi: θ = {theta}, φ = {phi}. Kürenin her noktası eşit olasılıklıydı.',
  'chip.random': 'rastgele',
  'measure.manyN': '{n} kopyayı ölç',
  'measure.axisErr': 'Eksen okunamadı. 1/4 ya da 45° gibi yaz; θn 0 ile π arasında olmalı.',
  'story.axis': 'Artık n = ({nx}, {ny}, {nz}) ekseni boyunca ölçülüyor: her atış "+n mi, −n mi?" diye sorar; P(+n) = (1 + r·n)/2.',
  'tomo.label': 'ölçülen',
  'tomo.out': 'Kurulan: ({x}, {y}, {z}) ± {s} · gerçek: ({rx}, {ry}, {rz}) · fark {d}',
  'story.tomo': 'X, Y ve Z\'nin her birinde {n} kopya ölçüldü ve ok ortalamalardan yeniden kuruldu (kesikli). Kopya arttıkça gerçeğine yaklaşır: sapma 1/√N gibi küçülür. Kübitin kendisine dokunulmadı.',
  'task.start': 'Başla',
  'task.again': 'Yeniden dene',
  'task.done': 'Çözüldü',
  'task.goal': 'hedef',
  'task.gates': 'Kullanılan kapı: {k}',
  'task.gatesMax': 'Kullanılan kapı: {k} / {m}',
  'task.solved': 'Çözüldü! Laboratuvar doğruluyor.',
  'task.tooMany': 'Bu görevin izin verdiğinden fazla kapı kullandın. Geri al ya da baştan başla.',
  'task.gatesOnly': 'Bu görevde yalnız kapı kullanılabilir. Son adımı geri al ya da baştan başla.',
  'task.going': 'Devam et.',
  'task.flip.title': 'Biti çevir',
  'task.flip.goal': '|0⟩\'dan başla. Tek kapıyla |1⟩\'e ulaş.',
  'task.plus.title': 'Bir süperpozisyon kur',
  'task.plus.goal': '|0⟩\'dan başla. Z ölçümünün 50/50 olduğu |+⟩\'ya tek kapıyla ulaş.',
  'task.toi.title': 'Y eksenine',
  'task.toi.goal': '|0⟩\'dan başla. İki kapıyla |i⟩\'ye ulaş.',
  'task.home.title': 'Eve dönüş',
  'task.home.goal': '|−i⟩\'den başla. Oku en fazla iki kapıyla |0⟩\'a geri getir.',
  'task.minus.title': 'Ölçülebilen bir faz',
  'task.minus.goal': '|0⟩\'dan başla. Z ölçümleri 50/50 çıksın, X ölçümleri ise hep |−⟩ versin. En fazla iki kapı; bu kez halka yok. Tahminini Ölçüm sekmesinde kopya ölçerek sınayabilirsin (tek ölçüm görevi bozar).',
  'task.odds.title': 'Dörtte üç',
  'task.odds.goal': 'Oku öyle ayarla ki Z ölçümü dört seferin üçünde |0⟩ versin. Her araç serbest. İpucu: P(|0⟩) = cos²(θ/2).',
  'story.typedAngles': 'Yazılan açılarla ayarlandı: θ = {theta}, φ = {phi}.',
  'story.typedAmps': 'α = {a}, β = {b} genlikleriyle ayarlandı.{norm} Global faz atılır: küre yalnız |0⟩ ile |1⟩ arasındaki bağıl fazı gösterir.',
  'exact.normalised': ' |α|² + |β|² = 1 olsun diye ikisi de {n} ile bölündü.',
  'exact.errAngles': 'Açılar okunamadı. 1/3, 0.25π ya da 60° gibi yaz; θ 0 ile π arasında olmalı.',
  'exact.errAmps': 'α ya da β okunamadı. 1/√2, 0.6+0.8i ya da i/2 gibi yaz; ikisi birden 0 olamaz.',
  'formula.mixed': 'karışık: ρ = ½(I + r·σ), r = {r}; tek bir |ψ⟩ yok',
  'autorotate': 'Oto-dönüş: {state}',
  'on': 'AÇIK',
  'off': 'KAPALI',
  'share.copied': 'Bağlantı kopyalandı',
  'share.failed': 'Kopyalanamadı: bağlantı adres çubuğunda',
  'custom.error': '0,5π, π/4 ya da 0,25 gibi sayılar yaz',
  'sp.chapterOf': 'Bölüm {n} / {total}',
  'sp.minRead': '~{m} dk okuma',
  'sp.prev': 'ÖNCEKİ BÖLÜM',
  'sp.next': 'SONRAKİ BÖLÜM',
  'sp.mixup': '§ YAYGIN KARIŞIKLIK',
  'sp.math': 'MATEMATİĞİ GÖSTER',
  'sp.expand': '[FORMÜLLERİ AÇ]',
  'sp.sources': 'Kaynaklar',
  'sp.fig': 'ŞEKİL',
  'sp.theta': 'Kutupsal açı (teta)',
  'sp.phi': 'Azimut açısı (fi)',
  'sp.r': 'Uzunluk r',
  'sp.basis': 'Ölçüm tabanı',
  'sp.once': 'Bir kez ölç',
  'sp.many': '1.000 kopyayı ölç',
  'sp.latest': 'Son atış:',
  'sp.ready': 'HAZIR',
  'sp.total': 'Toplam atış: {n}',
  'sp.tick': 'Siyah iğne: öngörü',
  'sp.gates': 'Kapılar',
  'sp.reset': '|0⟩ DURUMUNA DÖN',
  'sp.state': 'Durum vektörü: θ = {t}, φ = {p}, r = {r}',
  'sp.both': 'İkisinden de 1.000 kopya ölç',
  'sp.qubitA': 'KÜBİT A',
  'sp.qubitB': 'KÜBİT B',
  'sp.t': 'Dolanıklık t',
  'sp.reduced': 'Her kübit tek başına: |r| = {r}, Tr ρ² = {p}',
  'sp.noFigure': 'BU BÖLÜMDE ŞEKİL YOK',
  'sp.predicted': '{basis} tabanı öngörüsü:',
  'tag.qubit': 'BİTLER VE KÜBİTLER',
  'tag.angles': 'DURUM GEOMETRİSİ',
  'tag.measure': 'ÖLÇÜM VE ÇÖKÜŞ',
  'tag.phase': 'GLOBAL VE BAĞIL FAZ',
  'tag.gates': 'ÜNİTER DÖNMELER',
  'tag.mixed': 'SAF VE KARIŞIK DURUMLAR',
  'tag.entanglement': 'İKİ KÜBİT',
  'tag.limits': 'RESMİN SINIRLARI',
  'ref.theory': 'Kuram ve kuantum formalizmi',
  'ref.teaching': 'Öğretim ve pedagoji',
  'ref.research': 'Öğrenme araştırmaları',
  'ref.tools': 'Araçlar ve simülatörler',
  'ref.count': '{n} kayıt',
  'ref.nd': 't.y.',
};
